Refactor 5-app-infra-step
GoogleCloudPlatform/terraform-google-enterprise-genai pull request #48
Opened 2024-06-11 14:16 UTC by mariammartins

Hey folks, this PR contains:

- 5-app-infra refactoring step
- Update of steps to deploy 5-app-infra locally
- Changing step 6-machine-learning to "vertex-ai-machine-learning-pipeline" as an example

2024-06-11 14:28 UTC, caetano-colin requested changes
Some style changes

2024-06-11 14:28 UTC, caetano-colin commented on examples/vertex-ai-machine-learning-pipeline/README.md
> +# Vertex-ai-machine-learning-pipeline
adjust title

2024-06-11 14:28 UTC, caetano-colin commented on examples/vertex-ai-machine-learning-pipeline/README.md
> +### BIG QUERY
```suggestion
### Big Query
```

2024-06-11 14:28 UTC, caetano-colin commented on examples/vertex-ai-machine-learning-pipeline/README.md
> +### MACHINE LEARNING PIPELINE
```suggestion
### MACHINE LEARNING PIPELINE
```
```suggestion
### MACHINE LEARNING PIPELINE
```
```suggestion
### Machine Learning Pipeline
```

2024-06-11 14:28 UTC, caetano-colin commented on examples/vertex-ai-machine-learning-pipeline/README.md
> +### 3. Configure variables in compile_pipeline.py and runpipeline.py
```suggestion
#### 3. Configure variables in compile_pipeline.py and runpipeline.py
```

2024-06-11 14:28 UTC, caetano-colin commented on examples/vertex-ai-machine-learning-pipeline/README.md
> +### 4. Merge and deploy
```suggestion
#### 4. Merge and deploy
```

2024-06-11 14:28 UTC, caetano-colin commented on examples/vertex-ai-machine-learning-pipeline/README.md
> +### 5. Model Validation
```suggestion
#### 5. Model Validation
```

2024-06-11 18:59 UTC, caetano-colin commented
Some things to be done before merge:

- Adjust main README.md on section [6. ml-pipeline](https://github.com/mariammartins/terraform-google-enterprise-genai/blob/refactor/5-app-infra-step/6-ml-pipeline). Remove the section and add on readme a section about the examples, and link the example there.

2024-06-11 19:30 UTC, sleighton2022 commented
Linting fails

2024-06-12 14:52 UTC, caetano-colin commented on README.md
> +* [Machine-learning-pipeline](./examples/machine-learning-pipeline)
```suggestion
* [machine-learning-pipeline](./examples/machine-learning-pipeline)
```

2024-06-12 15:07 UTC, mariammartins commented
> Linting fails

Fixed

2024-06-12 19:08 UTC, renato-rudnicki commented on examples/machine-learning-pipeline/README.md
> +# Machile Learning Pipeline Overview
Machile Learning Pipeline Overview
```suggestion
# Machine Learning Pipeline Overview
```

2024-06-12 19:10 UTC, renato-rudnicki commented on examples/machine-learning-pipeline/README.md
> +# Machile Learning Pipeline Overview
Just a small typo.

2024-06-13 17:01 UTC, merged